### ISSUE TITLE
Lister le coût du matériel 

### ISSUE THREAD

**Issue by joalbalade** [joalbalade/Petit-focus-sur-l-optique#5]

**Comment by Polaire12** [comment]
https://www.ovio-optics.com/pack-camera-numerique-optique-et-filtres-ovisio-as-202972.html
300 euros le kit contenant Une caméra et un banc optique. X2

https://vevor.fr/products/kit-de-266pcs-266-lentilles-dessai-optique-jante-boitier-en-alu-cadre-dessai?gclid=CjwKCAiAxJSPBhAoEiwAeO_fP93vWEWtwTsSgvb5j9Q5EkO2ZHMfAQ7yFofFPRNmUNrjydPeYH6nCxoCvmQQAvD_BwE
250 euros 
160 x lentilles sphériques
80 x lentilles cylindriques
12 x prismes


https://www.laserpointeur.com/c-41_95-p-10017.html
Pointeurs laser 124 euros quantité X4
